//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 11/18/2015 6:40:07 PM
namespace ABSGeneral.Model
{
    
    /// <summary>
    /// There are no comments for NIIDDbModel.NIID_MotorDetails_Online in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NIID_NO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NIIDDbModel", Name="NIID_MotorDetails_Online")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NIID_MotorDetails_Online : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NIID_MotorDetails_Online object.
        /// </summary>
        /// <param name="nIID_NO">Initial value of NIID_NO.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static NIID_MotorDetails_Online CreateNIID_MotorDetails_Online(int nIID_NO)
        {
            NIID_MotorDetails_Online nIID_MotorDetails_Online = new NIID_MotorDetails_Online();
            nIID_MotorDetails_Online.NIID_NO = nIID_NO;
            return nIID_MotorDetails_Online;
        }
        /// <summary>
        /// There are no comments for property NIID_NO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int NIID_NO
        {
            get
            {
                return this._NIID_NO;
            }
            set
            {
                this.OnNIID_NOChanging(value);
                this.ReportPropertyChanging("NIID_NO");
                this._NIID_NO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NIID_NO");
                this.OnNIID_NOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _NIID_NO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_NOChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_NOChanged();
        /// <summary>
        /// There are no comments for property NIID_Username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Username
        {
            get
            {
                return this._NIID_Username;
            }
            set
            {
                this.OnNIID_UsernameChanging(value);
                this.ReportPropertyChanging("NIID_Username");
                this._NIID_Username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Username");
                this.OnNIID_UsernameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Username;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_UsernameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_UsernameChanged();
        /// <summary>
        /// There are no comments for property NIID_Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Password
        {
            get
            {
                return this._NIID_Password;
            }
            set
            {
                this.OnNIID_PasswordChanging(value);
                this.ReportPropertyChanging("NIID_Password");
                this._NIID_Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Password");
                this.OnNIID_PasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Password;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PasswordChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PasswordChanged();
        /// <summary>
        /// There are no comments for property NIID_NiaNaicomID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_NiaNaicomID
        {
            get
            {
                return this._NIID_NiaNaicomID;
            }
            set
            {
                this.OnNIID_NiaNaicomIDChanging(value);
                this.ReportPropertyChanging("NIID_NiaNaicomID");
                this._NIID_NiaNaicomID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_NiaNaicomID");
                this.OnNIID_NiaNaicomIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_NiaNaicomID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_NiaNaicomIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_NiaNaicomIDChanged();
        /// <summary>
        /// There are no comments for property NIID_PolicyNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_PolicyNo
        {
            get
            {
                return this._NIID_PolicyNo;
            }
            set
            {
                this.OnNIID_PolicyNoChanging(value);
                this.ReportPropertyChanging("NIID_PolicyNo");
                this._NIID_PolicyNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_PolicyNo");
                this.OnNIID_PolicyNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_PolicyNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PolicyNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PolicyNoChanged();
        /// <summary>
        /// There are no comments for property NIID_InsuredName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_InsuredName
        {
            get
            {
                return this._NIID_InsuredName;
            }
            set
            {
                this.OnNIID_InsuredNameChanging(value);
                this.ReportPropertyChanging("NIID_InsuredName");
                this._NIID_InsuredName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_InsuredName");
                this.OnNIID_InsuredNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_InsuredName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_InsuredNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_InsuredNameChanged();
        /// <summary>
        /// There are no comments for property NIID_ContactAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ContactAddress
        {
            get
            {
                return this._NIID_ContactAddress;
            }
            set
            {
                this.OnNIID_ContactAddressChanging(value);
                this.ReportPropertyChanging("NIID_ContactAddress");
                this._NIID_ContactAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ContactAddress");
                this.OnNIID_ContactAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ContactAddress;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ContactAddressChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ContactAddressChanged();
        /// <summary>
        /// There are no comments for property NIID_GSMNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_GSMNo
        {
            get
            {
                return this._NIID_GSMNo;
            }
            set
            {
                this.OnNIID_GSMNoChanging(value);
                this.ReportPropertyChanging("NIID_GSMNo");
                this._NIID_GSMNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_GSMNo");
                this.OnNIID_GSMNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_GSMNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GSMNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GSMNoChanged();
        /// <summary>
        /// There are no comments for property NIID_Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Email
        {
            get
            {
                return this._NIID_Email;
            }
            set
            {
                this.OnNIID_EmailChanging(value);
                this.ReportPropertyChanging("NIID_Email");
                this._NIID_Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Email");
                this.OnNIID_EmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Email;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EmailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EmailChanged();
        /// <summary>
        /// There are no comments for property NIID_EffectiveCoverDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_EffectiveCoverDate
        {
            get
            {
                return this._NIID_EffectiveCoverDate;
            }
            set
            {
                this.OnNIID_EffectiveCoverDateChanging(value);
                this.ReportPropertyChanging("NIID_EffectiveCoverDate");
                this._NIID_EffectiveCoverDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_EffectiveCoverDate");
                this.OnNIID_EffectiveCoverDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_EffectiveCoverDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EffectiveCoverDateChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EffectiveCoverDateChanged();
        /// <summary>
        /// There are no comments for property NIID_ExpirationDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ExpirationDate
        {
            get
            {
                return this._NIID_ExpirationDate;
            }
            set
            {
                this.OnNIID_ExpirationDateChanging(value);
                this.ReportPropertyChanging("NIID_ExpirationDate");
                this._NIID_ExpirationDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ExpirationDate");
                this.OnNIID_ExpirationDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ExpirationDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ExpirationDateChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ExpirationDateChanged();
        /// <summary>
        /// There are no comments for property NIID_TypeOfCover in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_TypeOfCover
        {
            get
            {
                return this._NIID_TypeOfCover;
            }
            set
            {
                this.OnNIID_TypeOfCoverChanging(value);
                this.ReportPropertyChanging("NIID_TypeOfCover");
                this._NIID_TypeOfCover = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_TypeOfCover");
                this.OnNIID_TypeOfCoverChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_TypeOfCover;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_TypeOfCoverChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_TypeOfCoverChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleCategory
        {
            get
            {
                return this._NIID_VehicleCategory;
            }
            set
            {
                this.OnNIID_VehicleCategoryChanging(value);
                this.ReportPropertyChanging("NIID_VehicleCategory");
                this._NIID_VehicleCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleCategory");
                this.OnNIID_VehicleCategoryChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleCategory;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleCategoryChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleCategoryChanged();
        /// <summary>
        /// There are no comments for property NIID_EngineNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_EngineNo
        {
            get
            {
                return this._NIID_EngineNo;
            }
            set
            {
                this.OnNIID_EngineNoChanging(value);
                this.ReportPropertyChanging("NIID_EngineNo");
                this._NIID_EngineNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_EngineNo");
                this.OnNIID_EngineNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_EngineNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineNoChanged();
        /// <summary>
        /// There are no comments for property NIID_ChasisNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ChasisNo
        {
            get
            {
                return this._NIID_ChasisNo;
            }
            set
            {
                this.OnNIID_ChasisNoChanging(value);
                this.ReportPropertyChanging("NIID_ChasisNo");
                this._NIID_ChasisNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ChasisNo");
                this.OnNIID_ChasisNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ChasisNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ChasisNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ChasisNoChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleColor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleColor
        {
            get
            {
                return this._NIID_VehicleColor;
            }
            set
            {
                this.OnNIID_VehicleColorChanging(value);
                this.ReportPropertyChanging("NIID_VehicleColor");
                this._NIID_VehicleColor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleColor");
                this.OnNIID_VehicleColorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleColor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleColorChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleColorChanged();
        /// <summary>
        /// There are no comments for property NIID_YearofMake in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_YearofMake
        {
            get
            {
                return this._NIID_YearofMake;
            }
            set
            {
                this.OnNIID_YearofMakeChanging(value);
                this.ReportPropertyChanging("NIID_YearofMake");
                this._NIID_YearofMake = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_YearofMake");
                this.OnNIID_YearofMakeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_YearofMake;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_YearofMakeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_YearofMakeChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleMake in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleMake
        {
            get
            {
                return this._NIID_VehicleMake;
            }
            set
            {
                this.OnNIID_VehicleMakeChanging(value);
                this.ReportPropertyChanging("NIID_VehicleMake");
                this._NIID_VehicleMake = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleMake");
                this.OnNIID_VehicleMakeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleMake;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleMakeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleMakeChanged();
        /// <summary>
        /// There are no comments for property NIID_RegistrationNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_RegistrationNo
        {
            get
            {
                return this._NIID_RegistrationNo;
            }
            set
            {
                this.OnNIID_RegistrationNoChanging(value);
                this.ReportPropertyChanging("NIID_RegistrationNo");
                this._NIID_RegistrationNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_RegistrationNo");
                this.OnNIID_RegistrationNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_RegistrationNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_RegistrationNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_RegistrationNoChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleType
        {
            get
            {
                return this._NIID_VehicleType;
            }
            set
            {
                this.OnNIID_VehicleTypeChanging(value);
                this.ReportPropertyChanging("NIID_VehicleType");
                this._NIID_VehicleType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleType");
                this.OnNIID_VehicleTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleType;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleTypeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleTypeChanged();
        /// <summary>
        /// There are no comments for property NIID_EngineCapacity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_EngineCapacity
        {
            get
            {
                return this._NIID_EngineCapacity;
            }
            set
            {
                this.OnNIID_EngineCapacityChanging(value);
                this.ReportPropertyChanging("NIID_EngineCapacity");
                this._NIID_EngineCapacity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_EngineCapacity");
                this.OnNIID_EngineCapacityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_EngineCapacity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineCapacityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineCapacityChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleModel in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleModel
        {
            get
            {
                return this._NIID_VehicleModel;
            }
            set
            {
                this.OnNIID_VehicleModelChanging(value);
                this.ReportPropertyChanging("NIID_VehicleModel");
                this._NIID_VehicleModel = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleModel");
                this.OnNIID_VehicleModelChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleModel;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleModelChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleModelChanged();
        /// <summary>
        /// There are no comments for property NIID_SumAssured in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_SumAssured
        {
            get
            {
                return this._NIID_SumAssured;
            }
            set
            {
                this.OnNIID_SumAssuredChanging(value);
                this.ReportPropertyChanging("NIID_SumAssured");
                this._NIID_SumAssured = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_SumAssured");
                this.OnNIID_SumAssuredChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_SumAssured;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_SumAssuredChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_SumAssuredChanged();
        /// <summary>
        /// There are no comments for property NIID_Premium in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Premium
        {
            get
            {
                return this._NIID_Premium;
            }
            set
            {
                this.OnNIID_PremiumChanging(value);
                this.ReportPropertyChanging("NIID_Premium");
                this._NIID_Premium = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Premium");
                this.OnNIID_PremiumChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Premium;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PremiumChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PremiumChanged();
        /// <summary>
        /// There are no comments for property NIID_CoverNoteNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_CoverNoteNo
        {
            get
            {
                return this._NIID_CoverNoteNo;
            }
            set
            {
                this.OnNIID_CoverNoteNoChanging(value);
                this.ReportPropertyChanging("NIID_CoverNoteNo");
                this._NIID_CoverNoteNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_CoverNoteNo");
                this.OnNIID_CoverNoteNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_CoverNoteNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CoverNoteNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CoverNoteNoChanged();
        /// <summary>
        /// There are no comments for property NIID_CertificateNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_CertificateNo
        {
            get
            {
                return this._NIID_CertificateNo;
            }
            set
            {
                this.OnNIID_CertificateNoChanging(value);
                this.ReportPropertyChanging("NIID_CertificateNo");
                this._NIID_CertificateNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_CertificateNo");
                this.OnNIID_CertificateNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_CertificateNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CertificateNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CertificateNoChanged();
        /// <summary>
        /// There are no comments for property NIID_GeographicalZone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_GeographicalZone
        {
            get
            {
                return this._NIID_GeographicalZone;
            }
            set
            {
                this.OnNIID_GeographicalZoneChanging(value);
                this.ReportPropertyChanging("NIID_GeographicalZone");
                this._NIID_GeographicalZone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_GeographicalZone");
                this.OnNIID_GeographicalZoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_GeographicalZone;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GeographicalZoneChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GeographicalZoneChanged();
        /// <summary>
        /// There are no comments for property NIID_Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Status
        {
            get
            {
                return this._NIID_Status;
            }
            set
            {
                this.OnNIID_StatusChanging(value);
                this.ReportPropertyChanging("NIID_Status");
                this._NIID_Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Status");
                this.OnNIID_StatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Status;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_StatusChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_StatusChanged();
        /// <summary>
        /// There are no comments for property NIID_ReturnMessage in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ReturnMessage
        {
            get
            {
                return this._NIID_ReturnMessage;
            }
            set
            {
                this.OnNIID_ReturnMessageChanging(value);
                this.ReportPropertyChanging("NIID_ReturnMessage");
                this._NIID_ReturnMessage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ReturnMessage");
                this.OnNIID_ReturnMessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ReturnMessage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ReturnMessageChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ReturnMessageChanged();
        /// <summary>
        /// There are no comments for property NIID_ProcessDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> NIID_ProcessDate
        {
            get
            {
                return this._NIID_ProcessDate;
            }
            set
            {
                this.OnNIID_ProcessDateChanging(value);
                this.ReportPropertyChanging("NIID_ProcessDate");
                this._NIID_ProcessDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NIID_ProcessDate");
                this.OnNIID_ProcessDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _NIID_ProcessDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ProcessDateChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ProcessDateChanged();
        /// <summary>
        /// There are no comments for property NIID_UploadDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> NIID_UploadDate
        {
            get
            {
                return this._NIID_UploadDate;
            }
            set
            {
                this.OnNIID_UploadDateChanging(value);
                this.ReportPropertyChanging("NIID_UploadDate");
                this._NIID_UploadDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NIID_UploadDate");
                this.OnNIID_UploadDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _NIID_UploadDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_UploadDateChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_UploadDateChanged();
    }
    /// <summary>
    /// There are no comments for NIIDDbModel.NIID_MotorDetails in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NIID_Username
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NIIDDbModel", Name="NIID_MotorDetails")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class NIID_MotorDetails : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new NIID_MotorDetails object.
        /// </summary>
        /// <param name="nIID_Username">Initial value of NIID_Username.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static NIID_MotorDetails CreateNIID_MotorDetails(string nIID_Username)
        {
            NIID_MotorDetails nIID_MotorDetails = new NIID_MotorDetails();
            nIID_MotorDetails.NIID_Username = nIID_Username;
            return nIID_MotorDetails;
        }
        /// <summary>
        /// There are no comments for property NIID_Username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Username
        {
            get
            {
                return this._NIID_Username;
            }
            set
            {
                this.OnNIID_UsernameChanging(value);
                this.ReportPropertyChanging("NIID_Username");
                this._NIID_Username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NIID_Username");
                this.OnNIID_UsernameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Username;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_UsernameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_UsernameChanged();
        /// <summary>
        /// There are no comments for property NIID_Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Password
        {
            get
            {
                return this._NIID_Password;
            }
            set
            {
                this.OnNIID_PasswordChanging(value);
                this.ReportPropertyChanging("NIID_Password");
                this._NIID_Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Password");
                this.OnNIID_PasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Password;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PasswordChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PasswordChanged();
        /// <summary>
        /// There are no comments for property NIID_NiaNaicomID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_NiaNaicomID
        {
            get
            {
                return this._NIID_NiaNaicomID;
            }
            set
            {
                this.OnNIID_NiaNaicomIDChanging(value);
                this.ReportPropertyChanging("NIID_NiaNaicomID");
                this._NIID_NiaNaicomID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_NiaNaicomID");
                this.OnNIID_NiaNaicomIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_NiaNaicomID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_NiaNaicomIDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_NiaNaicomIDChanged();
        /// <summary>
        /// There are no comments for property NIID_PolicyNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_PolicyNo
        {
            get
            {
                return this._NIID_PolicyNo;
            }
            set
            {
                this.OnNIID_PolicyNoChanging(value);
                this.ReportPropertyChanging("NIID_PolicyNo");
                this._NIID_PolicyNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_PolicyNo");
                this.OnNIID_PolicyNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_PolicyNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PolicyNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PolicyNoChanged();
        /// <summary>
        /// There are no comments for property NIID_InsuredName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_InsuredName
        {
            get
            {
                return this._NIID_InsuredName;
            }
            set
            {
                this.OnNIID_InsuredNameChanging(value);
                this.ReportPropertyChanging("NIID_InsuredName");
                this._NIID_InsuredName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_InsuredName");
                this.OnNIID_InsuredNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_InsuredName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_InsuredNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_InsuredNameChanged();
        /// <summary>
        /// There are no comments for property NIID_ContactAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ContactAddress
        {
            get
            {
                return this._NIID_ContactAddress;
            }
            set
            {
                this.OnNIID_ContactAddressChanging(value);
                this.ReportPropertyChanging("NIID_ContactAddress");
                this._NIID_ContactAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ContactAddress");
                this.OnNIID_ContactAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ContactAddress;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ContactAddressChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ContactAddressChanged();
        /// <summary>
        /// There are no comments for property NIID_GSMNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_GSMNo
        {
            get
            {
                return this._NIID_GSMNo;
            }
            set
            {
                this.OnNIID_GSMNoChanging(value);
                this.ReportPropertyChanging("NIID_GSMNo");
                this._NIID_GSMNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_GSMNo");
                this.OnNIID_GSMNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_GSMNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GSMNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GSMNoChanged();
        /// <summary>
        /// There are no comments for property NIID_Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Email
        {
            get
            {
                return this._NIID_Email;
            }
            set
            {
                this.OnNIID_EmailChanging(value);
                this.ReportPropertyChanging("NIID_Email");
                this._NIID_Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Email");
                this.OnNIID_EmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Email;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EmailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EmailChanged();
        /// <summary>
        /// There are no comments for property NIID_EffectiveCoverDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_EffectiveCoverDate
        {
            get
            {
                return this._NIID_EffectiveCoverDate;
            }
            set
            {
                this.OnNIID_EffectiveCoverDateChanging(value);
                this.ReportPropertyChanging("NIID_EffectiveCoverDate");
                this._NIID_EffectiveCoverDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_EffectiveCoverDate");
                this.OnNIID_EffectiveCoverDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_EffectiveCoverDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EffectiveCoverDateChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EffectiveCoverDateChanged();
        /// <summary>
        /// There are no comments for property NIID_ExpirationDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ExpirationDate
        {
            get
            {
                return this._NIID_ExpirationDate;
            }
            set
            {
                this.OnNIID_ExpirationDateChanging(value);
                this.ReportPropertyChanging("NIID_ExpirationDate");
                this._NIID_ExpirationDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ExpirationDate");
                this.OnNIID_ExpirationDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ExpirationDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ExpirationDateChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ExpirationDateChanged();
        /// <summary>
        /// There are no comments for property NIID_TypeOfCover in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_TypeOfCover
        {
            get
            {
                return this._NIID_TypeOfCover;
            }
            set
            {
                this.OnNIID_TypeOfCoverChanging(value);
                this.ReportPropertyChanging("NIID_TypeOfCover");
                this._NIID_TypeOfCover = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_TypeOfCover");
                this.OnNIID_TypeOfCoverChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_TypeOfCover;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_TypeOfCoverChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_TypeOfCoverChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleCategory
        {
            get
            {
                return this._NIID_VehicleCategory;
            }
            set
            {
                this.OnNIID_VehicleCategoryChanging(value);
                this.ReportPropertyChanging("NIID_VehicleCategory");
                this._NIID_VehicleCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleCategory");
                this.OnNIID_VehicleCategoryChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleCategory;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleCategoryChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleCategoryChanged();
        /// <summary>
        /// There are no comments for property NIID_EngineNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_EngineNo
        {
            get
            {
                return this._NIID_EngineNo;
            }
            set
            {
                this.OnNIID_EngineNoChanging(value);
                this.ReportPropertyChanging("NIID_EngineNo");
                this._NIID_EngineNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_EngineNo");
                this.OnNIID_EngineNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_EngineNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineNoChanged();
        /// <summary>
        /// There are no comments for property NIID_ChasisNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ChasisNo
        {
            get
            {
                return this._NIID_ChasisNo;
            }
            set
            {
                this.OnNIID_ChasisNoChanging(value);
                this.ReportPropertyChanging("NIID_ChasisNo");
                this._NIID_ChasisNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ChasisNo");
                this.OnNIID_ChasisNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ChasisNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ChasisNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ChasisNoChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleColor in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleColor
        {
            get
            {
                return this._NIID_VehicleColor;
            }
            set
            {
                this.OnNIID_VehicleColorChanging(value);
                this.ReportPropertyChanging("NIID_VehicleColor");
                this._NIID_VehicleColor = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleColor");
                this.OnNIID_VehicleColorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleColor;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleColorChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleColorChanged();
        /// <summary>
        /// There are no comments for property NIID_YearofMake in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_YearofMake
        {
            get
            {
                return this._NIID_YearofMake;
            }
            set
            {
                this.OnNIID_YearofMakeChanging(value);
                this.ReportPropertyChanging("NIID_YearofMake");
                this._NIID_YearofMake = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_YearofMake");
                this.OnNIID_YearofMakeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_YearofMake;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_YearofMakeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_YearofMakeChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleMake in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleMake
        {
            get
            {
                return this._NIID_VehicleMake;
            }
            set
            {
                this.OnNIID_VehicleMakeChanging(value);
                this.ReportPropertyChanging("NIID_VehicleMake");
                this._NIID_VehicleMake = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleMake");
                this.OnNIID_VehicleMakeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleMake;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleMakeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleMakeChanged();
        /// <summary>
        /// There are no comments for property NIID_RegistrationNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_RegistrationNo
        {
            get
            {
                return this._NIID_RegistrationNo;
            }
            set
            {
                this.OnNIID_RegistrationNoChanging(value);
                this.ReportPropertyChanging("NIID_RegistrationNo");
                this._NIID_RegistrationNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_RegistrationNo");
                this.OnNIID_RegistrationNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_RegistrationNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_RegistrationNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_RegistrationNoChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleType
        {
            get
            {
                return this._NIID_VehicleType;
            }
            set
            {
                this.OnNIID_VehicleTypeChanging(value);
                this.ReportPropertyChanging("NIID_VehicleType");
                this._NIID_VehicleType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleType");
                this.OnNIID_VehicleTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleType;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleTypeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleTypeChanged();
        /// <summary>
        /// There are no comments for property NIID_EngineCapacity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_EngineCapacity
        {
            get
            {
                return this._NIID_EngineCapacity;
            }
            set
            {
                this.OnNIID_EngineCapacityChanging(value);
                this.ReportPropertyChanging("NIID_EngineCapacity");
                this._NIID_EngineCapacity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_EngineCapacity");
                this.OnNIID_EngineCapacityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_EngineCapacity;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineCapacityChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_EngineCapacityChanged();
        /// <summary>
        /// There are no comments for property NIID_VehicleModel in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_VehicleModel
        {
            get
            {
                return this._NIID_VehicleModel;
            }
            set
            {
                this.OnNIID_VehicleModelChanging(value);
                this.ReportPropertyChanging("NIID_VehicleModel");
                this._NIID_VehicleModel = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_VehicleModel");
                this.OnNIID_VehicleModelChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_VehicleModel;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleModelChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_VehicleModelChanged();
        /// <summary>
        /// There are no comments for property NIID_SumAssured in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_SumAssured
        {
            get
            {
                return this._NIID_SumAssured;
            }
            set
            {
                this.OnNIID_SumAssuredChanging(value);
                this.ReportPropertyChanging("NIID_SumAssured");
                this._NIID_SumAssured = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_SumAssured");
                this.OnNIID_SumAssuredChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_SumAssured;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_SumAssuredChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_SumAssuredChanged();
        /// <summary>
        /// There are no comments for property NIID_Premium in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Premium
        {
            get
            {
                return this._NIID_Premium;
            }
            set
            {
                this.OnNIID_PremiumChanging(value);
                this.ReportPropertyChanging("NIID_Premium");
                this._NIID_Premium = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Premium");
                this.OnNIID_PremiumChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Premium;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PremiumChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_PremiumChanged();
        /// <summary>
        /// There are no comments for property NIID_CoverNoteNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_CoverNoteNo
        {
            get
            {
                return this._NIID_CoverNoteNo;
            }
            set
            {
                this.OnNIID_CoverNoteNoChanging(value);
                this.ReportPropertyChanging("NIID_CoverNoteNo");
                this._NIID_CoverNoteNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_CoverNoteNo");
                this.OnNIID_CoverNoteNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_CoverNoteNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CoverNoteNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CoverNoteNoChanged();
        /// <summary>
        /// There are no comments for property NIID_CertificateNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_CertificateNo
        {
            get
            {
                return this._NIID_CertificateNo;
            }
            set
            {
                this.OnNIID_CertificateNoChanging(value);
                this.ReportPropertyChanging("NIID_CertificateNo");
                this._NIID_CertificateNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_CertificateNo");
                this.OnNIID_CertificateNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_CertificateNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CertificateNoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_CertificateNoChanged();
        /// <summary>
        /// There are no comments for property NIID_GeographicalZone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_GeographicalZone
        {
            get
            {
                return this._NIID_GeographicalZone;
            }
            set
            {
                this.OnNIID_GeographicalZoneChanging(value);
                this.ReportPropertyChanging("NIID_GeographicalZone");
                this._NIID_GeographicalZone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_GeographicalZone");
                this.OnNIID_GeographicalZoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_GeographicalZone;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GeographicalZoneChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_GeographicalZoneChanged();
        /// <summary>
        /// There are no comments for property NIID_Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_Status
        {
            get
            {
                return this._NIID_Status;
            }
            set
            {
                this.OnNIID_StatusChanging(value);
                this.ReportPropertyChanging("NIID_Status");
                this._NIID_Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_Status");
                this.OnNIID_StatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_Status;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_StatusChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_StatusChanged();
        /// <summary>
        /// There are no comments for property NIID_ReturnMessage in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NIID_ReturnMessage
        {
            get
            {
                return this._NIID_ReturnMessage;
            }
            set
            {
                this.OnNIID_ReturnMessageChanging(value);
                this.ReportPropertyChanging("NIID_ReturnMessage");
                this._NIID_ReturnMessage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NIID_ReturnMessage");
                this.OnNIID_ReturnMessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NIID_ReturnMessage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ReturnMessageChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ReturnMessageChanged();
        /// <summary>
        /// There are no comments for property NIID_ProcessDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> NIID_ProcessDate
        {
            get
            {
                return this._NIID_ProcessDate;
            }
            set
            {
                this.OnNIID_ProcessDateChanging(value);
                this.ReportPropertyChanging("NIID_ProcessDate");
                this._NIID_ProcessDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NIID_ProcessDate");
                this.OnNIID_ProcessDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _NIID_ProcessDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ProcessDateChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNIID_ProcessDateChanged();
    }
    /// <summary>
    /// There are no comments for NiidDbContext in the schema.
    /// </summary>
    public partial class NiidDbContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new NiidDbContext object using the connection string found in the 'NiidDbContext' section of the application configuration file.
        /// </summary>
        public NiidDbContext() : 
                base("name=NiidDbContext", "NiidDbContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new NiidDbContext object.
        /// </summary>
        public NiidDbContext(string connectionString) : 
                base(connectionString, "NiidDbContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new NiidDbContext object.
        /// </summary>
        public NiidDbContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "NiidDbContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for NIID_MotorDetails_Online in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<NIID_MotorDetails_Online> NIID_MotorDetails_Online
        {
            get
            {
                if ((this._NIID_MotorDetails_Online == null))
                {
                    this._NIID_MotorDetails_Online = base.CreateQuery<NIID_MotorDetails_Online>("[NIID_MotorDetails_Online]");
                }
                return this._NIID_MotorDetails_Online;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<NIID_MotorDetails_Online> _NIID_MotorDetails_Online;
        /// <summary>
        /// There are no comments for NIID_MotorDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<NIID_MotorDetails> NIID_MotorDetails
        {
            get
            {
                if ((this._NIID_MotorDetails == null))
                {
                    this._NIID_MotorDetails = base.CreateQuery<NIID_MotorDetails>("[NIID_MotorDetails]");
                }
                return this._NIID_MotorDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<NIID_MotorDetails> _NIID_MotorDetails;
        /// <summary>
        /// There are no comments for NIID_MotorDetails_Online in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToNIID_MotorDetails_Online(NIID_MotorDetails_Online nIID_MotorDetails_Online)
        {
            base.AddObject("NIID_MotorDetails_Online", nIID_MotorDetails_Online);
        }
        /// <summary>
        /// There are no comments for NIID_MotorDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToNIID_MotorDetails(NIID_MotorDetails nIID_MotorDetails)
        {
            base.AddObject("NIID_MotorDetails", nIID_MotorDetails);
        }
    }
}
